### ISSUE TITLE
L2 - An error on `base` or `token` could leave the whole pool frozen

### ISSUE THREAD

**Issue by PhABC** [arcadeum/niftyswap#13]
> 
> If any of the two contracts of the tokens encounters an error and it stops being able to perform transfers the whole pool it's affected, making the associated funds on the other token impossible to withdraw.
> 
> Consider adding an aditional `removeLiquidity` parameter that allows the withdrawal of only `base` or only `token`.
> 
> Similar issuees had happened on Uniswap before (https://twitter.com/UniswapExchange/status/1072286773554876416) and (https://blog.synthetix.io/guide-on-migrating-seth-liquidity/)

By @Agusx1211

**Comment by PhABC** [comment]
This seems very difficult to prevent in practice since the act of removing liquidity should *not* impact the baseReserve/tokenReserve ratio. Somehow we would need to "lock" an exchange, preventing trades but allowing liquidity providers to withdraw the non-problematic token. 

Similar to Uniswap's philiosophy, an ERC-1155 token that fails to be transferred outside expected conditions would violate ERC-1155 standard and should not be used in Niftyswap unless Niftyswap is forked and modified to support it.

**Comment by Agusx1211** [comment]
The ratio changing while removing liquidity shouldn’t pose an issue, in fact, if it's done incorrectly it only harms the user withdrawing liquidity, it would be the equivalent of withdrawing liquidity in a regular way and then "donating" the locked tokes to the pool, the ratio changes but it generates an arbitrage opportunity and the remaining liquidity providers should end up with more tokens in total.

I understand that this is an edge case and shouldn’t pose an issue unless the ERC-1155 get's paused.
