### ISSUE TITLE
N1 - Token trades are not easily composable

### ISSUE THREAD

**Issue by PhABC** [arcadeum/niftyswap#14]
> The contracts don't allow users to perform trades using multiple pools with a single transaction; this could be partionally fixed by enabling the users to customize the `_data` field when transferring the newly acquired tokens, it could contain an aditional trade to be performed on another exchange.
> 
> It has to be noted that such a solution only works to enable trades between different exchange contracts. However, trades of different IDs on the same exchange contract would still not be possible, because of the usage of the reentrancy-lock.

By @Agusx1211

**Comment by PhABC** [comment]
One can make a simple wrapper contract to enable this feature, such as 

```solidity
contract TxnAggregator {

  struct ContractCall {
    address dest; // Contract to call
    bytes data;   // Calldata to pass to contract
  }

  /***********************************|
  |         BATCH TRANSACTIONS        |
  |__________________________________*/

  event Error(uint256 tx_id, bytes error);

  /**
   * @notice Will execute transactions with possibly different contracts
   * @param _txns    ContractCall struct array containing all the txns and target contract
   * @param _revert  To revert if a txn fail or to log the error
   */
  function executeTxns(ContractCall[] calldata _txns, bool _revert) external {
    // Execute all txns
    for (uint256 i = 0; i < _txns.length; i++) {
      (bool success, bytes memory resp) = _txns[i].dest.call(_txns[i].data);
      if (!success) {
        // Will either revert on error or log it
        if (_revert) {
          revert(string(resp));
        } else {
          emit Error(i, resp);
        }
      }
    }
  }
}
```

**Comment by Agusx1211** [comment]
Yes!, reviewing the issue I think that this is a better approach
