### ISSUE TITLE
N2 - Rounding up during while buying tokens or adding liquidity can be avoided

### ISSUE THREAD

**Issue by PhABC** [arcadeum/niftyswap#15]
> The `NiftyswapExchange` contracts always round transactions in a way that's favorable to the existing liquidity providers; this avoids them paying for inefficiencies when trading or adding liquidity, further aligning all incentives. This rounding it's always performed by increasing the resulting amount by `1`, although sufficient, it may lead to rounding calculations that don't require it.
> 
> Consider replacing it with a more precise `divRound` method `a / b + a % b == 0 ? 0 : 1`

By @Agusx1211

**Comment by PhABC** [comment]
This is a good suggestion, though I believe the rounding errors will be small enough that it won't really be an issue. Happy to be convinced otherwise!

**Comment by Agusx1211** [comment]
Rounding errors should be small enough for most of the tokens, but isn’t unheard of ERC20 tokens that have no decimals and end up with a minimal fragmentation unit of 1 dollar or so, and if a token like that were to be traded on Niftyswap it would be inefficient.

Also, the rounding on `getBuyPrice` could lead to lots of trades of round numbers to increase by 1 wei, maybe that could cause some confusion?

Last but not least, I think that is a simple fix that barely increases the gas usage of the contract.

**Comment by PhABC** [comment]
ccc6e9d741b46f366209381573388415aa07596a introduces a slightly difference method than commit above ^
